#!/bin/sh

name="coreos-live-iso"
tag="coreos-live-iso"

docker build -t $tag .

docker run -i --name $name $tag $@
ret=$?

if [ $ret -ne 0 ]; then
    echo "Build error."
    exit 1
fi

docker cp $name:/CoreOS.iso .

docker rm -f $name > /dev/null
